# Generated by Django 3.0.6 on 2020-06-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.TextField(default=' ')),
                ('location', models.TextField()),
                ('date', models.TextField()),
                ('total_cases', models.IntegerField()),
                ('new_cases', models.IntegerField()),
                ('total_deaths', models.IntegerField()),
                ('new_deaths', models.IntegerField()),
                ('Graph_cases', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('total_cases', models.IntegerField()),
                ('no_of_deaths', models.IntegerField()),
                ('cases_cured', models.IntegerField()),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='medical_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.TextField(default=' ')),
                ('Ischemic_heart_disease', models.TextField(default=' ')),
                ('Stroke', models.TextField(default=' ')),
                ('Bronchitis', models.TextField(default=' ')),
                ('HIV_AIDS', models.TextField(default=' ')),
                ('COPD', models.TextField(default=' ')),
                ('Diabetes_mellitus', models.TextField(default=' ')),
                ('Cirrhosis', models.TextField(default=' ')),
                ('Kidney_Disease', models.TextField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_Id', models.IntegerField()),
                ('name', models.TextField(default=' ')),
                ('phone_number', models.TextField(default=' ')),
                ('age', models.IntegerField()),
                ('address', models.TextField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='people3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.TextField(default=' ')),
                ('name', models.TextField(default=' ')),
                ('phone_number', models.TextField(default=' ')),
                ('age', models.IntegerField()),
                ('address', models.TextField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='quarantine_centres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre_name', models.TextField(default=' ')),
                ('centre_id', models.TextField(default=' ')),
                ('capacity', models.TextField(default=' ')),
                ('address', models.TextField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Travel_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_Id', models.TextField(default=' ')),
                ('april_16', models.TextField(default=' ')),
                ('april_17', models.TextField(default=' ')),
                ('april_18', models.TextField(default=' ')),
                ('april_19', models.TextField(default=' ')),
                ('april_20', models.TextField(default=' ')),
                ('april_21', models.TextField(default=' ')),
                ('april_22', models.TextField(default=' ')),
                ('april_23', models.TextField(default=' ')),
                ('april_24', models.TextField(default=' ')),
                ('april_25', models.TextField(default=' ')),
                ('april_26', models.TextField(default=' ')),
                ('april_27', models.TextField(default=' ')),
                ('april_28', models.TextField(default=' ')),
                ('april_29', models.TextField(default=' ')),
                ('april_30', models.TextField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='victims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victim_id', models.TextField(default=' ')),
                ('centre_id', models.TextField(default=' ')),
                ('admit_date', models.TextField(default=' ')),
            ],
        ),
    ]
