# Generated by Django 3.0.6 on 2020-06-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel_history',
            old_name='person_Id',
            new_name='person_id',
        ),
    ]
