# Generated by Django 3.0.6 on 2020-06-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_auto_20200605_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel_history2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.TextField(default=' ')),
                ('april_16', models.TextField(default=' ')),
                ('april_17', models.TextField(default=' ')),
                ('april_18', models.TextField(default=' ')),
                ('april_19', models.TextField(default=' ')),
                ('april_20', models.TextField(default=' ')),
                ('april_21', models.TextField(default=' ')),
                ('april_22', models.TextField(default=' ')),
                ('april_23', models.TextField(default=' ')),
                ('april_24', models.TextField(default=' ')),
                ('april_25', models.TextField(default=' ')),
                ('april_26', models.TextField(default=' ')),
                ('april_27', models.TextField(default=' ')),
                ('april_28', models.TextField(default=' ')),
                ('april_29', models.TextField(default=' ')),
                ('april_30', models.TextField(default=' ')),
            ],
        ),
    ]
